### ISSUE TITLE
Latest update still shows update available

### ISSUE THREAD

**Issue by drilus** [turnermm/Updatable-Snippets-for-Dokuwiki#27]
When I update the plugin Dokuwiki still shows the plugin as having an update.

<img width="1072" alt="screen shot 2017-02-23 at 12 05 08 pm" src="https://cloud.githubusercontent.com/assets/1356350/23270044/85d5395a-f9c0-11e6-9f94-ecca96ca267d.png">

**Comment by turnermm** [comment]
I probably failed to synch the date on the plugin page with the github distro

**Comment by turnermm** [comment]
Should be fixed now.

**Comment by drilus** [comment]
It's fixed.

Thanks!

**Comment by ghost** [comment]
Cropping up again... Even when manually installing the plugin, it still shows as updateable...

**Comment by turnermm** [comment]
Should be fixed

**Comment by ghost** [comment]
Yupp, fixed again. Thanks!
